# -*- coding: utf-8 -*-
"""NLP.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GMJeFF2IU01PojDy_vaAxedqpm_hFWGc
"""

!pip install spacy

!pip install spacy-streamlit

!python3 -m spacy download en

!pip install pyngrok

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# #Core packages
# import streamlit as st
# 
# #NLP packages
# import spacy
# import spacy_streamlit as ss
# from spacy import displacy
# nlp = spacy.load('en')
# 
# def main():
#   "NLP app with Streamlit"
#   st.title("NLP APP")
#   menu = ["Home", "Tokens", "NER", "Query"]
#   choice = st.sidebar.selectbox("Menu", menu)
# 
#   if choice == "Home":
#     st.subheader("Visualizer")
#     raw_text = st.text_area("Enter text here", " ")
#     docs = nlp(raw_text)
#     if st.button("Visualize"):
#       ss.visualize_parser(docs)
#       
# 
#   elif choice == "Tokens":
#     st.subheader("Tokenizer")
#     raw_text = st.text_area("Your Text", "")
#     docs = nlp(raw_text)
#     if st.button("Tokenize"):
#       ss.visualize_tokens(docs, attrs=['idx', 'text', 'pos_', 'lemma_', 'like_num'])
# 
#   elif choice == "NER":
#     st.subheader("Named Entity Recognizer")
#     raw_text = st.text_area("Enter text here")
#     docs = nlp(raw_text)
#     if st.button("NER"):
#       ss.visualize_ner(docs, labels=nlp.get_pipe('ner').labels)
#       
#   elif choice == "Query":
#     st.subheader("Query for spacy")
#     raw_text = st.text_area("Enter text here")
#     docs = nlp(raw_text)
#     answer = spacy.explain(raw_text)
#     if st.button("Explain"):
#       st.write(answer)
# 
# if __name__== '__main__':
#   main()

!ngrok authtoken XXXXXXXX

!ngrok

!streamlit run app.py&>/dev/null&

!pgrep streamlit

from pyngrok import ngrok

publ_url = ngrok.connect(port='8501')

publ_url

ngrok.kill()